### ISSUE TITLE
希望实现Flask框架的一些特性

### ISSUE THREAD

**Issue by gnuos** [twiglab/twig#4]
希望实现类似于 Flask 的 Blueprint 和 url_for 特性，可以考虑使用 NamedRoute 实现出来，可以选择给路由添加名称，使用 url_for 这样的功能可以直接返回对应的路由 URL 或者 handler

**Comment by it512** [comment]
url_for 由于Ctx#URL提供，目前只能工作在当前路由的NamedRoute上（后续会取消这个限制）
Blueprint由Mounter接口提供，github.com/twiglab/twig-extra/tprof中有个简单的实现可供参考
